query GetNotes {
  notes {
    id
    title
    url
    color
    folderId
    createdAt
    updatedAt
  }
}

query GetNotesByFolderId($folderId: String) {
  notes(folderId: $folderId) {
    id
    title
    url
    color
    folderId
    createdAt
    updatedAt
  }
}

